apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: master
spec:
  workspaces:
    - name: shared-data
    - name: harbor-auth
  tasks:
    - name: clone
      taskRef:
        resolver: hub
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: version
            value: "0.7"
      params:
        - name: url
          value: $(params.git_url)
        - name: revision
          value: $(params.git_revision)
      workspaces:
        - name: output
          workspace: shared-data
    - name: docker
      runAfter:
        - clone
      taskRef:
        resolver: hub
        params:
          - name: kind
            value: task
          - name: name
            value: kaniko
          - name: version
            value: "0.6"
      params:
        - name: IMAGE
          value: harbor.atte.cloud/library/blog:$(params.git_revision)
        - name: DOCKERFILE
          value: ./Dockerfile.blog
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: harbor-auth


